export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const EDIT_PSEUDO_SUCCESS = 'EDIT_PSEUDO_SUCCESS';
export const EDIT_PSEUDO_ERROR = 'EDIT_PSEUDO_ERROR';

export const GET_REMARKS = 'GET_REMARKS';
export const GET_REMARK = 'GET_REMARK';
export const ADD_REMARK = 'ADD_REMARK';
export const DELETE_REMARK = 'DELETE_REMARK';
export const REMARKS_LOADING = 'REMARKS_LOADING';
export const REMARK_ERROR = 'REMARK_ERROR';


export const ADD_ANSWER = 'ADD_ANSWER';
export const REMOVE_ANSWER = 'REMOVE_ANSWER'

export const UPDATE_ANSWER_LIKES = 'UPDATE_ANSWER_LIKES';
export const UPDATE_LIKES = 'UPDATE_LIKES';

export const UPDATE_ANSWER_SIGNALS = 'UPDATE_ANSWER_SIGNALS';
export const UPDATE_SIGNALS = 'UPDATE_SIGNALS'

export const GET_USERS = "GET_USERS";
export const DELETE_USER = "DELETE_USER";
export const USERS_LOADING = "USERS_LOADING";
export const USER_ERROR = "USER_ERROR";
export const REMOVE_ADMIN_SUCCESS = "REMOVE_ADMIN_SUCCESS";
export const REMOVE_ADMIN_ERROR = "REMOVE_ADMIN_ERROR";
export const UPDATE_ADMIN = "UPDATE_ADMIN";


