export const GET_REMARKS = 'GET_REMARKS';
export const ADD_REMARK = 'ADD_REMARK';
export const DELETE_REMARK = 'DELETE_REMARK';
export const REMARKS_LOADING = 'REMARKS_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';